version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlite-data:
